# Generated by Django 5.1.3 on 2024-11-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id_uzytkownika', models.IntegerField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('rola_id_rola', models.IntegerField()),
                ('ilosc_dni_urlopowych', models.IntegerField(blank=True, null=True)),
                ('zalegly_urlop', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Uzytkownik',
                'managed': False,
            },
        ),
    ]
