# Generated by Django 5.1.3 on 2024-11-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_wniosek_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ewidencja_cp',
            fields=[
                ('id_ewidencji', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('godziny_pracy', models.IntegerField()),
                ('Uzytkownik_id_uzytkownika', models.IntegerField()),
            ],
            options={
                'db_table': 'ewidencja_cp',
                'managed': False,
            },
        ),
    ]
