# Generated by Django 5.1.3 on 2024-11-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_ewidencja_cp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logowanie',
            fields=[
                ('id_logowania', models.AutoField(primary_key=True, serialize=False)),
                ('id_uzytkownika', models.IntegerField()),
                ('login', models.CharField(max_length=50)),
                ('haslo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'logowanie',
                'managed': False,
            },
        ),
    ]
